spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ms_empleados
          uri: http://localhost:8600
          predicates:
            - Path=/api/empleados/**
        - id: ms-empresas
          uri: http://localhost:8500
          predicates:
            - Path=/api/empresas/**

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    registerWithEureka: true
    fetchRegistry: true
